services:
    _defaults:
      autowire: true      # Automatically injects dependencies in your services.
      autoconfigure: true

    Corp\EiisBundle\Service\EiisIntegrationService:
        public: true
        class: Corp\EiisBundle\Service\EiisIntegrationService

    eiis.update.notification.subscriber:
        class: Corp\EiisBundle\Event\UpdateNotificationSubscriber
        public: true
        tags:
            - { name: kernel.event_listener, event: eiis.notification.update }

#    corp_eiis.admin.eiis_log:
#        class: Corp\EiisBundle\Admin\EiisLogAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: admin, label: EiisLog, model_class: Corp\EiisBundle\Entity\EiisLog }
#        public: true

    Corp\EiisBundle\Command\UpdateLocalDataCommand:
        tags:
            - { name: console.command }

