services:
    _defaults:
      autowire: true      # Automatically injects dependencies in your services.
      autoconfigure: true
    eiis.service:
        class: Corp\EiisBundle\Service\EiisIntegrationService
        calls:
             - [assignContainer, ['@service_container']]
    eiis.update.notification.subscriber:
        class: Corp\EiisBundle\Event\UpdateNotificationSubscriber
        public: true
        tags:
            - { name: kernel.event_listener, event: eiis.notification.update }
        calls:
             - [assignContainer, ['@service_container']]

    corp_eiis.admin.eiis_log:
        class: Corp\EiisBundle\Admin\EiisLogAdmin
        arguments: [~, Corp\EiisBundle\Entity\EiisLog, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EiisLog }
        public: true
    Corp\EiisBundle\Command\UpdateLocalDataCommand:
        tags:
            - { name: console.command }

